module.exports ={
  'secretKey': '+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y',
  'mongoUrl': 'mongodb://localhost/onlineproctore',
  'email': 'cleanframeiiit@gmail.com',
  'emailPassword': 'clean_frame2',
  'emailService': 'gmail',
  'baseEmail': '@iiita.ac.in',
  'projectName': 'OnlineProctorE',
  'baseLink': 'https://onlineproctore.iiita.ac.in',
  'student' : 294,
  'ta' : 747,
  'faculty' : 960,
  'staff' : 523,
  'multipleFace': 239,
  'mobile': 554,
  'screen': 796,
  'headPose': 211,
  'webPlagAPI': "d22734a8387807ec63de86ff641e1bff",
  'webPlagURL': 'https://www.prepostseo.com/apis/checkPlag'
};